use cs2110_active_learning;
truncate module;
truncate question;
truncate answer;
insert into module (name) values ('Advanced C'),('Assembly'),('Bits'),('Digital Logic'),('I/O'),('Intro to C'),('LC-3'),('Pointers and Arrays'),('Stack and Calling Convention'),('Von Neumann');

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'Unsigned Binary','Convert 55 to unsigned binary.','In unsigned binary, there is no sign bit; each bit contributes a positive value.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Convert 55 to unsigned binary.'),'0011 0111',1),((select question_id from question where content = 'Convert 55 to unsigned binary.'),'1100 1001 ',0),((select question_id from question where content = 'Convert 55 to unsigned binary.'),'0110 0110',0),((select question_id from question where content = 'Convert 55 to unsigned binary.'),'0010 0101',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'2''s Complement','Convert -55 to 2''s complement binary.','2''s complement notation uses the leading bit as the sign - 1 indicates a negative number and 0 indicates a positive number. For an n-bit number, 2''s complement representation can be thought of as subtracting 2^n from the unsigned binary of the given n-bit number . E.g. You are given the number 1111 1111, which is 255 in unsigned binary. The 2''s complement interpretation of this number can be thought of as 255 - 2^8 = -1. A handy trick is that -1 is always represented as all 1s in binar regardless of the length of the number.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Convert -55 to 2''s complement binary.'),'1100 1001',1),((select question_id from question where content = 'Convert -55 to 2''s complement binary.'),'0011 0111',0),((select question_id from question where content = 'Convert -55 to 2''s complement binary.'),'1011 0111',0),((select question_id from question where content = 'Convert -55 to 2''s complement binary.'),'0100 1001',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'Unsigned Binary Range','What range of numbers can be represented with 8 bits in unsigned binary?','In unsigned binary, n bits can represent all integers from 0 to 2^n -1.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What range of numbers can be represented with 8 bits in unsigned binary?'),'0-255',1),((select question_id from question where content = 'What range of numbers can be represented with 8 bits in unsigned binary?'),'0-256',0),((select question_id from question where content = 'What range of numbers can be represented with 8 bits in unsigned binary?'),'1-256',0),((select question_id from question where content = 'What range of numbers can be represented with 8 bits in unsigned binary?'),'-128-127',0),((select question_id from question where content = 'What range of numbers can be represented with 8 bits in unsigned binary?'),'-127-128',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'2''s Complement Binary Range','What range of numbers can be represented with 8 bits in 2''s complement?','In 2''s complement binary, an n bit number can represent all integers from -(2^(n-1)) to (2^(n-1)) - 1.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What range of numbers can be represented with 8 bits in 2''s complement?'),'-128-127',1),((select question_id from question where content = 'What range of numbers can be represented with 8 bits in 2''s complement?'),'0-255',0),((select question_id from question where content = 'What range of numbers can be represented with 8 bits in 2''s complement?'),'-127-128',0),((select question_id from question where content = 'What range of numbers can be represented with 8 bits in 2''s complement?'),'1-256',0),((select question_id from question where content = 'What range of numbers can be represented with 8 bits in 2''s complement?'),'-255-0',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'Bitwise Operators: &','What is the result of 0001 0111 & 1100 1100?','In the expression C = A & B, each bit in C will be a 1 if and only if the corresponding bits in A and B are also 1. In other words, the & operator performs an AND operation on each pair of bits in A and B and puts the result in C. ');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the result of 0001 0111 & 1100 1100?'),'0000  0100',1),((select question_id from question where content = 'What is the result of 0001 0111 & 1100 1100?'),'1101 1111',0),((select question_id from question where content = 'What is the result of 0001 0111 & 1100 1100?'),'1101 1010',0),((select question_id from question where content = 'What is the result of 0001 0111 & 1100 1100?'),'1111 1011',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'Bitwise Operators: |','What is the result of 0001 0111 | 1100 1100?','In the expression C = A | B, each bit in C will be a 1 if either of the corresponding bits in A and B are 1. In other words, the | operator performs an OR operation on each pair of bits in A and B and puts the result in C. ');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the result of 0001 0111 | 1100 1100?'),'1101 1111',1),((select question_id from question where content = 'What is the result of 0001 0111 | 1100 1100?'),'0000  0100',0),((select question_id from question where content = 'What is the result of 0001 0111 | 1100 1100?'),'1101 1010',0),((select question_id from question where content = 'What is the result of 0001 0111 | 1100 1100?'),'1111 1011',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'Bitwise Operators: ^','What is the result of 0001 0111 ^ 1100 1100?','In the expression C = A 6 B, each bit in C will be a 1 if the corresponding bits in A and B are different. In other words, the ^ operator performs an XOR operation on each pair of bits in A and B and puts the result in C. ');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the result of 0001 0111 ^ 1100 1100?'),'1101 1011',1),((select question_id from question where content = 'What is the result of 0001 0111 ^ 1100 1100?'),'1101 1111',0),((select question_id from question where content = 'What is the result of 0001 0111 ^ 1100 1100?'),'0000  0100',0),((select question_id from question where content = 'What is the result of 0001 0111 ^ 1100 1100?'),'1101 1010',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'Bitwise Operators: ~','What is the result of ~ 0001 0111?','The ~ operator simply flips all the bits of its operand.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the result of ~ 0001 0111?'),'1110 1000',1),((select question_id from question where content = 'What is the result of ~ 0001 0111?'),'0001 0111',0),((select question_id from question where content = 'What is the result of ~ 0001 0111?'),'1110 1001',0),((select question_id from question where content = 'What is the result of ~ 0001 0111?'),'1111 1011',0),((select question_id from question where content = 'What is the result of ~ 0001 0111?'),'1101 1010',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'Bitwise Operators: <<','What is the result of 1100 1100 << 4?','The << operator shifts bits to the left, padding the number with 0s on the right. n << k is equivalent to n * 2^k.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the result of 1100 1100 << 4?'),'1100 0000',1),((select question_id from question where content = 'What is the result of 1100 1100 << 4?'),'0000 0000 ',0),((select question_id from question where content = 'What is the result of 1100 1100 << 4?'),'1100 1111',0),((select question_id from question where content = 'What is the result of 1100 1100 << 4?'),'1100 1100',0),((select question_id from question where content = 'What is the result of 1100 1100 << 4?'),'1000 0000',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'Bitwise Operators: >>','What is the result of 1100 1100 >> 4?','The >> operator shifts bits to the left, padding the number with the sign bit on the left. n >> k is equivalent to n / 2^k. E.g. 1110 1111 >> 2  == 1111 1011 and 0111 1111 >> 2 == 0001 1111.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the result of 1100 1100 >> 4?'),'1111 1100',1),((select question_id from question where content = 'What is the result of 1100 1100 >> 4?'),'1100 1100',0),((select question_id from question where content = 'What is the result of 1100 1100 >> 4?'),'0000 1100',0),((select question_id from question where content = 'What is the result of 1100 1100 >> 4?'),'0001 1000',0),((select question_id from question where content = 'What is the result of 1100 1100 >> 4?'),'1111 1000',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'Binary to Hex','What is the number 1101 0110 in hex?','Each group of 4 bits in a binary number corresponds to a hexadecimal digit. Hexadecimal uses the numbers 0-9 and the letters A-F to represent numbers from 0-16 in decimal.  ');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the number 1101 0110 in hex?'),'0xD6',1),((select question_id from question where content = 'What is the number 1101 0110 in hex?'),'0xC6',0),((select question_id from question where content = 'What is the number 1101 0110 in hex?'),'0x6D',0),((select question_id from question where content = 'What is the number 1101 0110 in hex?'),'0x6C',0),((select question_id from question where content = 'What is the number 1101 0110 in hex?'),'0xA4',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Bits'),'Hex to Binary','What is the number 0x2E in binary?','Each group of 4 bits in a binary number corresponds to a hexadecimal digit. Hexadecimal uses the numbers 0-9 and the letters A-F to represent numbers from 0-16 in decimal.  ');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the number 0x2E in binary?'),'0010 1110',1),((select question_id from question where content = 'What is the number 0x2E in binary?'),'0100 1111',0),((select question_id from question where content = 'What is the number 0x2E in binary?'),'1110 0010',0),((select question_id from question where content = 'What is the number 0x2E in binary?'),'1111 0010',0),((select question_id from question where content = 'What is the number 0x2E in binary?'),'1010 1010',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Digital Logic'),'Multiplexers','Given a multiplexer with n control bits, how many different inputs can the multiplexer accept? How many outputs does it produce?','A multiplexer (mux) with n control bits can have 2^n inputs. Each n-bit number on the control bits corresponds to a different input into the multiplexer. A multiplexer always has exactly one output.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Given a multiplexer with n control bits, how many different inputs can the multiplexer accept? How many outputs does it produce?'),'Input: 2^n; Output: 1',1),((select question_id from question where content = 'Given a multiplexer with n control bits, how many different inputs can the multiplexer accept? How many outputs does it produce?'),'Input: 1; Output: 2^n',0),((select question_id from question where content = 'Given a multiplexer with n control bits, how many different inputs can the multiplexer accept? How many outputs does it produce?'),'Input: n; Output 1',0),((select question_id from question where content = 'Given a multiplexer with n control bits, how many different inputs can the multiplexer accept? How many outputs does it produce?'),'Input: log2(n); Output: 1;',0),((select question_id from question where content = 'Given a multiplexer with n control bits, how many different inputs can the multiplexer accept? How many outputs does it produce?'),'Input: 2^n; Output: log2(n)',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Digital Logic'),'Transistors into Gates','How many transistors are necessary to build an AND gate?','<INSERT AN ATTACHMENT HERE. FIGURE OUT HOW TO DO THIS IN DB>');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'How many transistors are necessary to build an AND gate?'),'6',1),((select question_id from question where content = 'How many transistors are necessary to build an AND gate?'),'1',0),((select question_id from question where content = 'How many transistors are necessary to build an AND gate?'),'4',0),((select question_id from question where content = 'How many transistors are necessary to build an AND gate?'),'8',0),((select question_id from question where content = 'How many transistors are necessary to build an AND gate?'),'2',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Von Neumann'),'The Program Counter','The Program Counter (PC) holds:','The program counter (PC) indicates the address of the next instruction to fetch and execute.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'The Program Counter (PC) holds:'),'The address of the next instruction to be executed.',1),((select question_id from question where content = 'The Program Counter (PC) holds:'),'All legal op codes',0),((select question_id from question where content = 'The Program Counter (PC) holds:'),'The count of instructions executed.',0),((select question_id from question where content = 'The Program Counter (PC) holds:'),'Number of programs completed since the last boot.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Von Neumann'),'The Instruction Register','The Instruction Register (IR) holds','The instruction register (IR) holds the current instruction so that other datapath elements can parse relevant information from it.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'The Instruction Register (IR) holds'),'The instruction currently being executed.',1),((select question_id from question where content = 'The Instruction Register (IR) holds'),'The address of the next instruction to be executed.',0),((select question_id from question where content = 'The Instruction Register (IR) holds'),'All data needed to execute the current instruction.',0),((select question_id from question where content = 'The Instruction Register (IR) holds'),'All legal op codes.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Von Neumann'),'Central Idea','True or False: In the Von Neumann model of computer processing, code and data are stored in the same memory segments.','In the Von Neumann model, code and data are the same, and are both stored in memory. This is in contrast to a Harvard architecure, where code is read-only and stored in different memory segments.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'True or False: In the Von Neumann model of computer processing, code and data are stored in the same memory segments.'),'1',1),((select question_id from question where content = 'True or False: In the Von Neumann model of computer processing, code and data are stored in the same memory segments.'),'0',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'LC-3'),'Branching','If you don''t want the execution to proceed to the next instruction what must be changed?','The PC determines what the next instruction will be. By changing this value, we can change the program flow.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'If you don''t want the execution to proceed to the next instruction what must be changed?'),'Program Counter (PC)',1),((select question_id from question where content = 'If you don''t want the execution to proceed to the next instruction what must be changed?'),'Instruction Register (IR)',0),((select question_id from question where content = 'If you don''t want the execution to proceed to the next instruction what must be changed?'),'Memory Address Register (MAR)',0),((select question_id from question where content = 'If you don''t want the execution to proceed to the next instruction what must be changed?'),'Memory Data Register (MDR)',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'LC-3'),'General Purpose Registers','Is the PC considered to be a general-purpose register (GPR)?','The PC is not a general purpose register because it is not accessible via the LC-3''s ISA.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Is the PC considered to be a general-purpose register (GPR)?'),'0',1),((select question_id from question where content = 'Is the PC considered to be a general-purpose register (GPR)?'),'1',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'LC-3'),'Addressing Mode','What addressing mode is used by the following NOT instruction? [ 1001 | DR | SR | 111111]','Both DR and SR are register numbers. The registers are addressed as r0, r1, ... rn. An example instruction using NOT might look like "NOT r0, r1"');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What addressing mode is used by the following NOT instruction? [ 1001 | DR | SR | 111111]'),'Register',1),((select question_id from question where content = 'What addressing mode is used by the following NOT instruction? [ 1001 | DR | SR | 111111]'),'Immediate/Literal',0),((select question_id from question where content = 'What addressing mode is used by the following NOT instruction? [ 1001 | DR | SR | 111111]'),'PC-relative',0),((select question_id from question where content = 'What addressing mode is used by the following NOT instruction? [ 1001 | DR | SR | 111111]'),'Indirect',0),((select question_id from question where content = 'What addressing mode is used by the following NOT instruction? [ 1001 | DR | SR | 111111]'),'Base + Offset',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'LC-3'),'ISA','What does an ISA do?','The ISA specifies all the information about the computer that the software needs to be aware of; it defines how software interacts with the hardware.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What does an ISA do?'),'Provides an interface between software and hardware.',1),((select question_id from question where content = 'What does an ISA do?'),'Determines what kind of applications can run on a computer.',0),((select question_id from question where content = 'What does an ISA do?'),'Defines an application architecture.',0),((select question_id from question where content = 'What does an ISA do?'),'Gives details about all of the hardware in a computer.',0),((select question_id from question where content = 'What does an ISA do?'),'NaN',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'LC-3'),'RISC vs. CISC','True or False: The ISA (Instruction Set Architecture) of the LC-3 is an example of a CISC (Complex Instruction Set Computing) ISA. ','The RISC (Reduced Instruction Set Computing) ISA of the LC-3 contains 18 different instructions while the CISC x86 ISA contains hundreds of instructions.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'True or False: The ISA (Instruction Set Architecture) of the LC-3 is an example of a CISC (Complex Instruction Set Computing) ISA. '),'0',1),((select question_id from question where content = 'True or False: The ISA (Instruction Set Architecture) of the LC-3 is an example of a CISC (Complex Instruction Set Computing) ISA. '),'1',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'LC-3'),'Condition Codes','When are condition codes set?','A condition code is set after any time data is written to a general purpose register. This occurs with the following instructions: LD, LDI, LDR, LEA, AND, ADD, and NOT');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'When are condition codes set?'),'After any instruction that writes data to a general purpose register.',1),((select question_id from question where content = 'When are condition codes set?'),'After any instruction that reads data from a general purpose register.',0),((select question_id from question where content = 'When are condition codes set?'),'After any instruction that accesses memory.',0),((select question_id from question where content = 'When are condition codes set?'),'After any instruction.',0),((select question_id from question where content = 'When are condition codes set?'),'After any branching/jump instruction.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'LC-3'),'Addressability and Address Space','What are the addressability and address space of the LC-3, respectively?','Addressability refers to the unit of data that is present at each memory address.  The address space refers to the number of addresses available. The LC-3 is 16 bit addressable withan address space ranging from 0x0000-0xFFFF (65,536 addresses).');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What are the addressability and address space of the LC-3, respectively?'),'16 bits, 16 bits',1),((select question_id from question where content = 'What are the addressability and address space of the LC-3, respectively?'),'8 bits, 16 bits',0),((select question_id from question where content = 'What are the addressability and address space of the LC-3, respectively?'),'32 bits, 32 bits',0),((select question_id from question where content = 'What are the addressability and address space of the LC-3, respectively?'),'32 bits, 16 bits',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'LC-3'),'Address Space','True or False: All of the addresses in the LC-3''s address space are availble for the programmer to use.','All address are not available.  Only addresses in the range 0x3000 to 0xFDFF are available to the application programmer.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'True or False: All of the addresses in the LC-3''s address space are availble for the programmer to use.'),'0',1),((select question_id from question where content = 'True or False: All of the addresses in the LC-3''s address space are availble for the programmer to use.'),'1',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'LC-3'),'HALT?','What happens if there is no HALT instruction in your program?','The processor will begin to execute your data. As mentioned in the Von Neumann model of computing, code is data.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What happens if there is no HALT instruction in your program?'),'The processor will start to execute your data.',1),((select question_id from question where content = 'What happens if there is no HALT instruction in your program?'),'A memory boundary trap occurs.',0),((select question_id from question where content = 'What happens if there is no HALT instruction in your program?'),'The processor will stop anyways.',0),((select question_id from question where content = 'What happens if there is no HALT instruction in your program?'),'The processor will go back to the beginning of your program.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Assembly'),'Opcodes','What is an opcode?','An opcode is a mnemonic that represents an instruction to the processor. An instruction may take more than 1 clock cycle to complete.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is an opcode?'),'A mnemonic for an instruction.',1),((select question_id from question where content = 'What is an opcode?'),'A section of operational code in a program.',0),((select question_id from question where content = 'What is an opcode?'),'A directive indicating how the processor should interpret following code.',0),((select question_id from question where content = 'What is an opcode?'),'An argument to the operand.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Assembly'),'Operands','What is an operand?','An operand is an argument given to an opcode. When an opcode and its operands are assembled, we call that an "instruction".');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is an operand?'),'An argument for an opcode.',1),((select question_id from question where content = 'What is an operand?'),'An AND operation.',0),((select question_id from question where content = 'What is an operand?'),'A mnemonic for an instruction.',0),((select question_id from question where content = 'What is an operand?'),'A section of operational code in a program.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Assembly'),'What is a Label?','What does a label do?','A label is a symbol used by the assembler to reference a memory address; it is a level of indirection available to the assembly programmer.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What does a label do?'),'A label refers to a memory address in an assembly program.',1),((select question_id from question where content = 'What does a label do?'),'A label is used exclusively for branching targets.',0),((select question_id from question where content = 'What does a label do?'),'A label is a variable in assembly programs.',0),((select question_id from question where content = 'What does a label do?'),'A label refers to the name of the program.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Assembly'),'... and How are They Used?','Which of the following is NOT a use of a label?','Because a label references a memory address, it is not used with opcodes that function on registers.  However, it can be used as an operand when a memory address is needed.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Which of the following is NOT a use of a label?'),'ADD operand.',1),((select question_id from question where content = 'Which of the following is NOT a use of a label?'),'A branch target.',0),((select question_id from question where content = 'Which of the following is NOT a use of a label?'),'LD/ST operand.',0),((select question_id from question where content = 'Which of the following is NOT a use of a label?'),'LEA operand.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Assembly'),'Pseudo-Ops','What is a pseudo-op?','A pseudo-op is a directive to the assembler to do something specific at a location. This typically involves indicating the beginning or end of a program in memory or filling a memory address with a value.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is a pseudo-op?'),'A directive to the assembler.',1),((select question_id from question where content = 'What is a pseudo-op?'),'A "high-level" instruction that is composed of many atomic instructions.',0),((select question_id from question where content = 'What is a pseudo-op?'),'A comment in the assembly code.',0),((select question_id from question where content = 'What is a pseudo-op?'),'A no-operation (NOP) instruction.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Assembly'),'It''s a TRAP!','What is a TRAP?','A TRAP instruction makes a call to the operating system to do certain work, which is commonly I/O.  The HALT instruction is actually a mnemonic for TRAP x21, which is how the HALT instruction is actually implemented.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is a TRAP?'),'A call to the operating system to do something.',1),((select question_id from question where content = 'What is a TRAP?'),'A synonym for HALT',0),((select question_id from question where content = 'What is a TRAP?'),'An exception handling mechanism.',0),((select question_id from question where content = 'What is a TRAP?'),'A device or enclosure to catch animals.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Assembly'),'Control Flow','True or False: Not all control flow mechanisms (e.g. for, while, if/else, etc) in a language like C or Java can be implemented in assembly.','Any high-level operation can be transformed into assembly language. This is what compilers do!');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'True or False: Not all control flow mechanisms (e.g. for, while, if/else, etc) in a language like C or Java can be implemented in assembly.'),'0',1),((select question_id from question where content = 'True or False: Not all control flow mechanisms (e.g. for, while, if/else, etc) in a language like C or Java can be implemented in assembly.'),'1',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Assembly'),'Loading...','What is the result of the following instruction:&#10;FLAG: .fill 0x0040&#10;LEA R0, FLAG','The LEA instruction loads an address into a register. A label just refers to an address.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the result of the following instruction:&#10;FLAG: .fill 0x0040&#10;LEA R0, FLAG'),'R0 contains the address of FLAG.',1),((select question_id from question where content = 'What is the result of the following instruction:&#10;FLAG: .fill 0x0040&#10;LEA R0, FLAG'),'R0 contains the value 0x0040.',0),((select question_id from question where content = 'What is the result of the following instruction:&#10;FLAG: .fill 0x0040&#10;LEA R0, FLAG'),'FLAG contains the value of R0',0),((select question_id from question where content = 'What is the result of the following instruction:&#10;FLAG: .fill 0x0040&#10;LEA R0, FLAG'),'FLAG contains the address of R0',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Assembly'),'Still Loading...','What is the result of the following instruction:&#10;FLAG: .fill 0x0040&#10;LD R0, FLAG','LD loads the contents of an address into a register.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the result of the following instruction:&#10;FLAG: .fill 0x0040&#10;LD R0, FLAG'),'R0 contains the value 0x0040.',1),((select question_id from question where content = 'What is the result of the following instruction:&#10;FLAG: .fill 0x0040&#10;LD R0, FLAG'),'R0 contains the address of FLAG.',0),((select question_id from question where content = 'What is the result of the following instruction:&#10;FLAG: .fill 0x0040&#10;LD R0, FLAG'),'FLAG contains the value of R0',0),((select question_id from question where content = 'What is the result of the following instruction:&#10;FLAG: .fill 0x0040&#10;LD R0, FLAG'),'FLAG contains the address of R0',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Assembly'),'That''s a Lot of Branches','True or False: BR ADDRESS and BRNZP ADDRESS do the same thing.','The condition codes (NZP) after the BR indicate when to take the branch.  BR is just shorthand for the unconditional branch BRNZP, which would take the branch given any condition code.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'True or False: BR ADDRESS and BRNZP ADDRESS do the same thing.'),'1',1),((select question_id from question where content = 'True or False: BR ADDRESS and BRNZP ADDRESS do the same thing.'),'0',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Assembly'),'Operand Order','What are the roles of R0, R1, and R2, respectively, in the following instruction: ADD R0, R1, R2?','The destination register comes first in LC-3 assembly syntax, then a source register, and then either a second register or an immediate value.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What are the roles of R0, R1, and R2, respectively, in the following instruction: ADD R0, R1, R2?'),'Destination register, source register, source register.',1),((select question_id from question where content = 'What are the roles of R0, R1, and R2, respectively, in the following instruction: ADD R0, R1, R2?'),'Source register, source register, destination register.',0),((select question_id from question where content = 'What are the roles of R0, R1, and R2, respectively, in the following instruction: ADD R0, R1, R2?'),'Source register, destination register, source register.',0),((select question_id from question where content = 'What are the roles of R0, R1, and R2, respectively, in the following instruction: ADD R0, R1, R2?'),'Destination register, source register, unused.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'I/O'),'Memory Mapping','What is memory mapping?','Memory mapping refers to an I/O device''s registers being mapped directly to a memory address. This allows for the processor and programmer to use LD/ST and friends to manipulate the device.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is memory mapping?'),'Assigning an I/O device''s registers to a memory address.',1),((select question_id from question where content = 'What is memory mapping?'),'The process of assigning unique IDs to an I/O device on boot-up.',0),((select question_id from question where content = 'What is memory mapping?'),'The use of special registers to communicate with an I/O device.',0),((select question_id from question where content = 'What is memory mapping?'),'The process of segmenting memory into a map.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'I/O'),'N''Sync?','True or False: Polling is an asynchronous method for reading from external devices.','To poll a device is to repeatedly check whether or not the device is ready. This means that when the device is ready, the processor is immediately ready to read or write data from it.  In contrast, there is interrupt-driven I/O. This method relies on a ready-bit being set in the device''s control register. When this bit is set, an interrupt is triggered which can alter control flow of the program to handle the I/O communication.  Interrupt-driven I/O is magnitudes more efficient than polling, but takes more software and hardware effort to accomplish. For example, a processor handles keyboard input asynchronously. A keyboard emits in the order of 10s of events per second. Polling I/O would waste significant processor cycles waiting for an input (even 100 ms is an eternity for your i7), while interrupt-driven I/O would allow the processor to handle other tasks while handling input on demand.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'True or False: Polling is an asynchronous method for reading from external devices.'),'0',1),((select question_id from question where content = 'True or False: Polling is an asynchronous method for reading from external devices.'),'1',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Stack and Calling Convention'),'The Essential Opcodes','Which opcodes are used to call functions?','JSR and JSRR are used to jump to subroutines and set the link register appropriately.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Which opcodes are used to call functions?'),'JSR and JSRR',1),((select question_id from question where content = 'Which opcodes are used to call functions?'),'BR and JMP',0),((select question_id from question where content = 'Which opcodes are used to call functions?'),'LEA and JMP',0),((select question_id from question where content = 'Which opcodes are used to call functions?'),'LD and JMP',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Stack and Calling Convention'),'Saving State','How do we ensure that the calling function''s state is preserved after the function call?','Both the callee and caller save different parts of state on the stack.  The caller saves the important information regarding frame and stack pointers and the link register, while the callee will save and restore any registers that it plans to use for its calculations.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'How do we ensure that the calling function''s state is preserved after the function call?'),'Both the callee and caller save registers on the stack.',1),((select question_id from question where content = 'How do we ensure that the calling function''s state is preserved after the function call?'),'Only the caller saves registers on the stack.',0),((select question_id from question where content = 'How do we ensure that the calling function''s state is preserved after the function call?'),'Only the callee saves registers on the stack.',0),((select question_id from question where content = 'How do we ensure that the calling function''s state is preserved after the function call?'),'Parameters are only passed on the stack, so nothing needs to be done.',0),((select question_id from question where content = 'How do we ensure that the calling function''s state is preserved after the function call?'),'Parameters are only passed through registers, so nothing needs to be done.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Stack and Calling Convention'),'Stack Pointer... ?','What is the stack pointer?','The stack pointer is a register that holds the address of the next available location on the stack.  This register is callee saved in the LC-3 calling convention.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the stack pointer?'),'A register that contains the next available address in the stack.',1),((select question_id from question where content = 'What is the stack pointer?'),'A register that contains the last used address of the stack.',0),((select question_id from question where content = 'What is the stack pointer?'),'A variable in memory that indicates where the stack is.',0),((select question_id from question where content = 'What is the stack pointer?'),'The upper and lower bounds of the stack.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Stack and Calling Convention'),'Frame Pointer...?','What is the frame pointer?','The frame pointer is a register that holds an address of a specific point in a "frame".  A frame is defined as the context in which a function is called.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the frame pointer?'),'A register that contains the address of a fixed point into a frame.',1),((select question_id from question where content = 'What is the frame pointer?'),'The bounds of a function frame.',0),((select question_id from question where content = 'What is the frame pointer?'),'A variable in memory that indicates where the frame is.',0),((select question_id from question where content = 'What is the frame pointer?'),'A register that always points to a given frame.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Stack and Calling Convention'),'Caller Role','Which of the following is NOT a responsibility of the calling function?','The callee function saves SP and FP on the stack, as well as storing the return address, setting the return value, and updating the new FP.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Which of the following is NOT a responsibility of the calling function?'),'Saving the SP and FP on the stack.',1),((select question_id from question where content = 'Which of the following is NOT a responsibility of the calling function?'),'Pushing function arguments onto the stack.',0),((select question_id from question where content = 'Which of the following is NOT a responsibility of the calling function?'),'Executing JSR/JSRR to jump to the called function.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Stack and Calling Convention'),'One Simple Recursion Rule','What is the best way to think about recursion in the LC-3 calling convention?','The function simply calls itself. For example, if we have a recurisve factorial function int fac(int n) { if (n < 1) return 1; else return n * fac(n -1); }, fac() acts as a callee when execution enters the function, and acts as a callee when fac(n-1) is called.  This is no different than if we called some_other_fac(n-1). The calling convention is apathetic to the actual function being called.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the best way to think about recursion in the LC-3 calling convention?'),'One part of the recursive function is the caller, and other part of the recursive function is the callee; it''s just function calling another function.',1),((select question_id from question where content = 'What is the best way to think about recursion in the LC-3 calling convention?'),'NULL',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Intro to C'),'Have to Start Somewhere','As an application C programmer, what is the entry function for the application?','Just like in Java, an application written in C begins execution in main().');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'As an application C programmer, what is the entry function for the application?'),'main()',1),((select question_id from question where content = 'As an application C programmer, what is the entry function for the application?'),'init()',0),((select question_id from question where content = 'As an application C programmer, what is the entry function for the application?'),'start()',0),((select question_id from question where content = 'As an application C programmer, what is the entry function for the application?'),'begin()',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Intro to C'),'The Pre-what?','Broadly, what does the C preprocessor do?','The C preprocessor does text replacement and insertion. The most common uses are #include-ing files and #define-ing constants.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Broadly, what does the C preprocessor do?'),'Text replacement and insertion.',1),((select question_id from question where content = 'Broadly, what does the C preprocessor do?'),'Checking the validity of a program.',0),((select question_id from question where content = 'Broadly, what does the C preprocessor do?'),'Compiling a program.',0),((select question_id from question where content = 'Broadly, what does the C preprocessor do?'),'Transforming C into bytecode.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Intro to C'),'Header Files','True or False: Header files should not contain code.','Header files contain declarations of functions, macros, type definitions, and some constants. They should not, in most cases, contain code, as they will typically be included in many different locations throughout a program.  If code is located in a header file, it will also be included in many different files as a consequence.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'True or False: Header files should not contain code.'),'1',1),((select question_id from question where content = 'True or False: Header files should not contain code.'),'0',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Intro to C'),'Macros','Given the following macro and expression, what will be the value of a when the code is executed?&#10;#define ADD(n, m) n + m&#10;int a = ADD(10, 2) * 4;','Macros do not act like a function - they only do text replacement. Thus, the resulting expression after the ADD macro is replaced with the expression is 10 + 2 * 4, which evaluates to 10 + 8 = 18.  Always parenthesize your macros AND MACRO PARAMETERS (e.g. #define SQUARE(x) ((x) * (x))) to avoid this issue. You can view the result of macro expansion by compiling your code with gcc -E your_file.c.  As a rule of thumb, prefer a function to a macro unless the macro is very, very simple or the speed gains from a macro are absolutely necessary.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Given the following macro and expression, what will be the value of a when the code is executed?&#10;#define ADD(n, m) n + m&#10;int a = ADD(10, 2) * 4;'),'18',1),((select question_id from question where content = 'Given the following macro and expression, what will be the value of a when the code is executed?&#10;#define ADD(n, m) n + m&#10;int a = ADD(10, 2) * 4;'),'48',0),((select question_id from question where content = 'Given the following macro and expression, what will be the value of a when the code is executed?&#10;#define ADD(n, m) n + m&#10;int a = ADD(10, 2) * 4;'),'42',0),((select question_id from question where content = 'Given the following macro and expression, what will be the value of a when the code is executed?&#10;#define ADD(n, m) n + m&#10;int a = ADD(10, 2) * 4;'),'24',0),((select question_id from question where content = 'Given the following macro and expression, what will be the value of a when the code is executed?&#10;#define ADD(n, m) n + m&#10;int a = ADD(10, 2) * 4;'),'0',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Intro to C'),'Error Handling','True or False: C handles errors through exceptions, like any sane programming language.','C does not have an exception handling mechanism. C handles exceptional conditions through the return value of the function. For more details, visit errno.h or use the command "man errno".  Every function return value should be checked, with the exception of printf and fprintf.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'True or False: C handles errors through exceptions, like any sane programming language.'),'0',1),((select question_id from question where content = 'True or False: C handles errors through exceptions, like any sane programming language.'),'1',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Intro to C'),'Simple I/O','Which of the following specifiers and arguments would correctly print a hexadecimal representation of 16 to stdout in printf?','x is the specifier for printing a number in hexadecimal, while d is the specifier for printing a nummber. Use the command "man 3 printf" for more details on specifiers. printf is a convenient form of fprintf, which lets you choose the file to which to print. On a Unix-based system (i.e. Linux or MacOS), stdout, stdin, and stderr are all treated as files that can be read and written.  In fact, most physical devices on a Linux system are also treated as device.  Try looking at things in /dev/.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Which of the following specifiers and arguments would correctly print a hexadecimal representation of 16 to stdout in printf?'),'x, 16',1),((select question_id from question where content = 'Which of the following specifiers and arguments would correctly print a hexadecimal representation of 16 to stdout in printf?'),'d, 16',0),((select question_id from question where content = 'Which of the following specifiers and arguments would correctly print a hexadecimal representation of 16 to stdout in printf?'),'n, 16',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Intro to C'),'Functions','Which of the following is NOT a valid function signature?','C does not have public and private modifiers. The modifier "static", when used on a function, makes a function accessible only within the file in which it is declared.  Also, function declarations in C do not require variable names for the parameters, just the type.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Which of the following is NOT a valid function signature?'),'public void my_func(int x);',1),((select question_id from question where content = 'Which of the following is NOT a valid function signature?'),'int my_func(int, int);',0),((select question_id from question where content = 'Which of the following is NOT a valid function signature?'),'static void *my_func(void *arg, char c);',0),((select question_id from question where content = 'Which of the following is NOT a valid function signature?'),'void main(int argc, char **argv);',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Intro to C'),'Static','Which of the following is NOT a use of the "static" modifier?','The modifier "static" has many uses in C.  It restricts the scope of a variable or function to the file in which it is declared. When applied to a variable within a function, the variable is only initialized once, and then persists between repeated calls to that function. Essentially, the variable acts like it is static memory outside of a function, but can only be accessed from within the function.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Which of the following is NOT a use of the "static" modifier?'),'Attaching a function to a class instead of an instance of that class.',1),((select question_id from question where content = 'Which of the following is NOT a use of the "static" modifier?'),'Making a function-local variable''s value persist between function calls.',0),((select question_id from question where content = 'Which of the following is NOT a use of the "static" modifier?'),'Making a variable accessible only within a file.',0),((select question_id from question where content = 'Which of the following is NOT a use of the "static" modifier?'),'Making a function only accessible in a file.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Intro to C'),'Booleans','Which of the following values evaluates to a boolean false?','In C, the value 0 is false whether it is a pointer or integer; all other values are true, including negative numbers.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Which of the following values evaluates to a boolean false?'),'The null pointer.',1),((select question_id from question where content = 'Which of the following values evaluates to a boolean false?'),'An unitialized variable.',0),((select question_id from question where content = 'Which of the following values evaluates to a boolean false?'),'-1',0),((select question_id from question where content = 'Which of the following values evaluates to a boolean false?'),'~1',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Pointers and Arrays'),'Pointers','What is a pointer?','A pointer is simply a variable that holds the address of a variable.  For example, int *pa holds the address of an int or, equivalently, a pointer to an int. Pointers are incredibly simple at heart.  Imagine memory is like a sequence of lockers.  A pointer just tells which locker number something is in.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is a pointer?'),'A variable that holds an address.',1),((select question_id from question where content = 'What is a pointer?'),'An object.',0),((select question_id from question where content = 'What is a pointer?'),'A label.',0),((select question_id from question where content = 'What is a pointer?'),'A reference to another variable.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Pointers and Arrays'),'Dereferencing','What is the value of *pa after the following code is executed?&#10;int a = 10;&#10;int *pa = &a;&#10;a++;','*pa will be 11 after the code is executed. The ampersand (&) returns the address of a variable; it is very useful. Used on the right-hand side of an =, (e.g. int b = *pa;), the * operator dereferences a pointer, which means it gets the value from the address the pointer holds.  Going back to the locker analogy, it goes to the given locker number and takes out (really more like "reads") whatever is in there.  Using * on the left hand side of the = (e.g. *pa = 12;), writes the given value to wherever the pointer points. Again using the locker analogy, it goes to the given locker number and puts the given value into that locker.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the value of *pa after the following code is executed?&#10;int a = 10;&#10;int *pa = &a;&#10;a++;'),'11',1),((select question_id from question where content = 'What is the value of *pa after the following code is executed?&#10;int a = 10;&#10;int *pa = &a;&#10;a++;'),'10',0),((select question_id from question where content = 'What is the value of *pa after the following code is executed?&#10;int a = 10;&#10;int *pa = &a;&#10;a++;'),'undefined',0),((select question_id from question where content = 'What is the value of *pa after the following code is executed?&#10;int a = 10;&#10;int *pa = &a;&#10;a++;'),'0x6040',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Pointers and Arrays'),'Array v. Pointer','True or False: An array is identical to a pointer.','While arrays and pointers are equivalent and can largely be used in similar ways, they are absolutely not identical. An array is label to a fixed location in memory and cannot be reassigned after declaration.  A pointer is more general in that it is just a variable that holds the address of something. For a more detailed explanation, visit http://c-faq.com/aryptr/index.html.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'True or False: An array is identical to a pointer.'),'0',1),((select question_id from question where content = 'True or False: An array is identical to a pointer.'),'1',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Pointers and Arrays'),'Pointer Arithmetic','Given sizeof(int) == 4 and a byte-addressable memory, what is the value of the following expresion: ((int *) 0x3000) + 1 ?','Adding or subtracting from a pointer (i.e. pointer arithmetic) by an index automatically scales the index by sizeof(type_of_value).  This means that adding or subtracting from a pointer will give you the address of the next sequential element. To do a "normal" arithmetic operation on a pointer, cast the pointer to (char *) first so that the scaling value becomes 1 (because sizeof(char) is 1). ');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'Given sizeof(int) == 4 and a byte-addressable memory, what is the value of the following expresion: ((int *) 0x3000) + 1 ?'),'0x3004',1),((select question_id from question where content = 'Given sizeof(int) == 4 and a byte-addressable memory, what is the value of the following expresion: ((int *) 0x3000) + 1 ?'),'0x3001',0),((select question_id from question where content = 'Given sizeof(int) == 4 and a byte-addressable memory, what is the value of the following expresion: ((int *) 0x3000) + 1 ?'),'0x3000',0),((select question_id from question where content = 'Given sizeof(int) == 4 and a byte-addressable memory, what is the value of the following expresion: ((int *) 0x3000) + 1 ?'),'0x3008',0),((select question_id from question where content = 'Given sizeof(int) == 4 and a byte-addressable memory, what is the value of the following expresion: ((int *) 0x3000) + 1 ?'),'Undefined behavior',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Pointers and Arrays'),'The NULL Pointer','What happens when you dereference a NULL pointer?','Dereferencing a NULL pointer causes a Segmentation Fault, which occurs when you try to access memory you don''t own.  A seg fault happens because NULL == (void *)0, and you don''t own the memory at address 0 - the system owns that forever and for always.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What happens when you dereference a NULL pointer?'),'Segmentation Fault',1),((select question_id from question where content = 'What happens when you dereference a NULL pointer?'),'Null Pointer Exception',0),((select question_id from question where content = 'What happens when you dereference a NULL pointer?'),'Returns 0.',0),((select question_id from question where content = 'What happens when you dereference a NULL pointer?'),'Undefined behavior.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Pointers and Arrays'),'Indexing','What is the value of 5["abcdef"]?','The index operator ([index]) is just syntactic sugar for *(ptr + index).  Because addition is commutative and string literals can be treated like read-only arrays, silly expressions like the one in the question do actually work.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is the value of 5["abcdef"]?'),'f',1),((select question_id from question where content = 'What is the value of 5["abcdef"]?'),'That won''t compile.',0),((select question_id from question where content = 'What is the value of 5["abcdef"]?'),'e',0),((select question_id from question where content = 'What is the value of 5["abcdef"]?'),'Undefined behavior.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Advanced C'),'Please Don''t Do This','What is wrong with the following code: int *func(void) { int a = 10; return &a; }?','This snippet of code returns a pointer to a variable allocated on the stack.  Once func() returns, its stack frame will be automatically deallocated and probably used by another program.  This means that anything in that frame will be invalidated.  By returning a pointer that references a value in that frame, we are effectively pointing to undefined memory. Please never ever write code like this.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is wrong with the following code: int *func(void) { int a = 10; return &a; }?'),'It returns a pointer to a locally allocated variable.',1),((select question_id from question where content = 'What is wrong with the following code: int *func(void) { int a = 10; return &a; }?'),'It returns a pointer to a variable of the wrong type.',0),((select question_id from question where content = 'What is wrong with the following code: int *func(void) { int a = 10; return &a; }?'),'It doesn''t do anything useful.',0),((select question_id from question where content = 'What is wrong with the following code: int *func(void) { int a = 10; return &a; }?'),'Undefined behavior.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Advanced C'),'Dynamic Memory','What does malloc(size_t n) do?','malloc(n) allocates n bytes on the heap and returns a pointer to that data.  If malloc() fails, it will return NULL.  The heap is a region of memory that is not automatically allocated and deallocated like the stack is.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What does malloc(size_t n) do?'),'Allocates n bytes on the heap and returns a pointer to the beginning of the bytes.',1),((select question_id from question where content = 'What does malloc(size_t n) do?'),'Allocated n bytes on the stack and returns a pointer to it.',0),((select question_id from question where content = 'What does malloc(size_t n) do?'),'Makes a new object.',0),((select question_id from question where content = 'What does malloc(size_t n) do?'),'Undefined behavior.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Advanced C'),'We''re not in Javaland, anymore','When should you call free()?','As a counterpart to malloc(), free(void *ptr) releases (frees) the memory which is pointed at.  After you free() memory, you give it back to the operating system to manage, which means you can no longer access that memory. Trying to access free()ed memory typically results in a Segmentation Fault.  If you fail to free() memory, you create a memory leak - allocating memory that you can never give back to the operating system until your program terminates.  Unlike Java, an object is not destroyed when you set the pointer to NULL.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'When should you call free()?'),'When you want to release memory.',1),((select question_id from question where content = 'When should you call free()?'),'When a variable goes out of scope.',0),((select question_id from question where content = 'When should you call free()?'),'Never.',0),((select question_id from question where content = 'When should you call free()?'),'Immediately after malloc().',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Advanced C'),'What kind of pointer?!','What is a void *?','A void * is a pointer to any kind of data.  It is an address with no type associated.  As a consequence, you cannot derefence a void * until you cast it to a known type (e.g. char *, int *, etc).  In C, it is not required to explictly cast a void * when assigning to or from - you can just assign it directly with no explicit cast.');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What is a void *?'),'A type that can point to any kind of data.',1),((select question_id from question where content = 'What is a void *?'),'An invalid declaration.',0),((select question_id from question where content = 'What is a void *?'),'A typo.',0),((select question_id from question where content = 'What is a void *?'),'A type that points to void.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Advanced C'),'What Standard Data Structures?','What data structure does the following struct implement: struct mystery_ds { struct mystery_ds *next; void *data }; ?','A singly linked list can be easily implemented a struct that simply holds a pointer to the data and a pointer to the next node.  This is one of, if not the most, common data structure in C besides the basic array.  Because C does not provide a standard library of data structures like Java, it is up to the programmer to implement them manually.  All data structures in higher-level languages like Java can be implemented in C, also; the lack of garbage collection just makes it a little bit tougher.  ');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What data structure does the following struct implement: struct mystery_ds { struct mystery_ds *next; void *data }; ?'),'Singly linked list',1),((select question_id from question where content = 'What data structure does the following struct implement: struct mystery_ds { struct mystery_ds *next; void *data }; ?'),'BST',0),((select question_id from question where content = 'What data structure does the following struct implement: struct mystery_ds { struct mystery_ds *next; void *data }; ?'),'HashMap',0),((select question_id from question where content = 'What data structure does the following struct implement: struct mystery_ds { struct mystery_ds *next; void *data }; ?'),'Doubly linked list.',0),((select question_id from question where content = 'What data structure does the following struct implement: struct mystery_ds { struct mystery_ds *next; void *data }; ?'),'Bloom filter.',0);

insert into question (module_id,name,content,explanation) values ((select module_id from module where name = 'Advanced C'),'Function Pointer Syntax','What does the following do: typedef void *(*my_func)(int **, void*)?','A function pointer is simply the address of a function.  This allows functions to be passed around just like any other variable. Function pointer syntax looks like the following: return_type (*name)(param list, ...). When used in a typedef statement, the name becomes the name of the type, so a function that accepts a function pointer as a parameter may look like this: void fp_func(my_func arg);');
insert into answer (question_id,content,is_correct) values ((select question_id from question where content = 'What does the following do: typedef void *(*my_func)(int **, void*)?'),'Declares a type called "my_func" that is a function that returns a void * and takes an int ** and void * as parameters.',1),((select question_id from question where content = 'What does the following do: typedef void *(*my_func)(int **, void*)?'),'Causes a compilation error.',0),((select question_id from question where content = 'What does the following do: typedef void *(*my_func)(int **, void*)?'),'Declares a type called "my_func" that is a function that returns void and takes an int ** and void * as parameters.',0),((select question_id from question where content = 'What does the following do: typedef void *(*my_func)(int **, void*)?'),'Declares a type called "my_func" that is a function that returns a void ** and takes an int ** and void * as parameters.',0);

